// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250214200610_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple iPhone 15, 128GB, Black",
                            ImageUrl = "iphone15.jpg",
                            IsActive = true,
                            Name = "iPhone 15",
                            Price = 600m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Samsung Galaxy S23, 256GB, Phantom Black",
                            ImageUrl = "galaxys23.jpg",
                            IsActive = true,
                            Name = "Samsung Galaxy S23",
                            Price = 750m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 3,
                            Description = "Google Pixel 7, 128GB, Obsidian",
                            ImageUrl = "pixel7.jpg",
                            IsActive = true,
                            Name = "Google Pixel 7",
                            Price = 650m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            Description = "OnePlus 11, 256GB, Titan Black",
                            ImageUrl = "oneplus11.jpg",
                            IsActive = true,
                            Name = "OnePlus 11",
                            Price = 700m,
                            Stock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
